services:
  laravel:
    build:
      context: ./laravel11
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel11:/var/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
    networks:
      - multipedidos-network
      
  nginx-laravel:
    image: nginx:latest
    container_name: nginx-laravel
    ports:
      - "8000:80"
    volumes:
      - ./laravel11:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - multipedidos-network

  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=todolist-multipedidos
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - multipedidos-network

  angular:
    image: nginx:alpine
    container_name: angular-app
    volumes:
      - ./angular1.6:/usr/share/nginx/html
      - ./docker/angular/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4200:80
    networks:
      - multipedidos-network

volumes:
  mysql-data:    

networks:
  multipedidos-network:
    driver: bridge
